### ISSUE TITLE
Unable to start receiver swarajsaaj.smscodereader.receivers.OtpReader: java.lang.NullPointerException: cs == null

### ISSUE THREAD

**Issue by sharmad1205** [swarajsaaj/otpReader#1]
Hi, Please Help me Out. 
I have implemented this library...... and using OTPVerification Fragment.
Everything works fine when SMS is received from mySender. But in case When the SMS is from another user, the app crashes  and give the null pointer exception as 

Unable to start receiver swarajsaaj.smscodereader.receivers.OtpReader: java.lang.NullPointerException: cs == null

In onCreateView I use  
`OtpReader.bind(this, "XXXXXXX"); //Constant like BIZY not to be displayed
`
and my OTPreceived method is 
`@Override
    public void otpReceived(String messageText) {
//        Utils.showToast(mContext, messageText + "OTP");
        Pattern p = Pattern.compile("(|^)\\d{6}");
        if(messageText!=null) {
            Matcher m = p.matcher(messageText);
            if (m.find()) {
                et_OTP_verification.setText(m.group(0));
            } else {
                //something went wrong
            }
        }
        Log.d("Otp", messageText);
    }`

**Comment by abhishekmittal4007** [comment]
the same issue occurs with me.Please resolve it!

**Comment by anbarasuthresnathan** [comment]
Me too have same error any solution provided please share with me

**Comment by shubhamsardar07** [comment]
same here! do share the solution please...

**Comment by swarajsaaj** [comment]
@sharmad1205 @abhishekmittal4007 @MoSardy @anbarasuthresnathan 
Hello all, apologies for late reply, I am just in process of fixing this, will fix and release a new version soon.

**Comment by swarajsaaj** [comment]
@sharmad1205 @abhishekmittal4007 @MoSardy @anbarasuthresnathan 

Hi guys, New version 1.1 is released and this issue has been fixed for now.
You can update your library version and use.

Reason:- Issue was due to missing receiverString on switch between app broadcast receivers.
Solution:- A null check for receieverString.

A proper event register and unregister solution will be implemented in next release.


Please let know if it still exists.
